name: radio_over
description: "A minimalist internet radio + podcast mobile app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  audio_service: ^0.18.19
  audio_session: ^0.2.0
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  http: ^1.6.0
  just_audio: ^0.10.6
  path: ^1.9.0
  path_provider: ^2.1.6
  share_plus: ^13.3.0
  shared_preferences: ^2.5.5
  xml: ^7.0.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
